/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type BatchStatus = "staging" | "in_progress" | "completed";

export const BatchStatus = {
    Staging: "staging",
    InProgress: "in_progress",
    Completed: "completed",
} as const;
