/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

export interface BatchStatusResponse {
    status?: Scale.BatchStatus;
    pending?: number;
    error?: number;
    completed?: number;
    canceled?: number;
}
