/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Batch {
    project?: string;
    name?: string;
    status?: string;
    callback?: string;
    createdAt?: string;
}
