/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ScaleApi } from "@fern-api/scale";

export interface BatchList {
    docs?: ScaleApi.Batch[];
    total?: number;
    limit?: number;
    offset?: number;
    hasMore?: boolean;
}
