/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const AssignTeammate: core.serialization.ObjectSchema<
    serializers.studio.AssignTeammate.Raw,
    Scale.studio.AssignTeammate
> = core.serialization.object({
    emails: core.serialization.list(core.serialization.string()),
    projects: core.serialization.list(core.serialization.string()),
});

export declare namespace AssignTeammate {
    interface Raw {
        emails: string[];
        projects: string[];
    }
}
