/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const Assignment: core.serialization.Schema<serializers.studio.Assignment.Raw, Scale.studio.Assignment> =
    core.serialization.list(core.serialization.string());

export declare namespace Assignment {
    type Raw = string[];
}
