/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const BatchStatus: core.serialization.Schema<serializers.BatchStatus.Raw, ScaleApi.BatchStatus> =
    core.serialization.enum_(["staging", "in_progress", "completed"]);

export declare namespace BatchStatus {
    type Raw = "staging" | "in_progress" | "completed";
}
