/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../core";

export const Batch: core.serialization.ObjectSchema<serializers.Batch.Raw, Scale.Batch> = core.serialization.object({
    project: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    callback: core.serialization.string().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
});

export declare namespace Batch {
    interface Raw {
        project?: string | null;
        name?: string | null;
        status?: string | null;
        callback?: string | null;
        created_at?: string | null;
    }
}
