/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Teammate {
    /** Teammate email */
    email: string;
    /** Teammate role, can be of `labeler` (Studio only), `member`, `manager`. */
    role: string;
    /** Teammate company */
    company?: string;
    /** Teammate first name */
    firstName?: string;
    /** Teammate last name */
    lastName?: string;
    /** Is teammate a Studio labeler? */
    isStudioLabeler?: boolean;
    /** If teammate status is `invited`, this field indicates when the invitation will expire. */
    expiry?: string;
}
