/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../core";

export const CreateBatchRequest: core.serialization.Schema<
    serializers.CreateBatchRequest.Raw,
    Scale.CreateBatchRequest
> = core.serialization.object({
    project: core.serialization.string(),
    name: core.serialization.string(),
    callback: core.serialization.string().optional(),
    calibrationBatch: core.serialization.property("calibration_batch", core.serialization.boolean().optional()),
    selfLabelBatch: core.serialization.property("self_label_batch", core.serialization.boolean().optional()),
});

export declare namespace CreateBatchRequest {
    interface Raw {
        project: string;
        name: string;
        callback?: string | null;
        calibration_batch?: boolean | null;
        self_label_batch?: boolean | null;
    }
}
