/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateBatchRequest {
    project: string;
    name: string;
    callback?: string;
    calibrationBatch?: boolean;
    selfLabelBatch?: boolean;
}
