/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListBatchesRequest {
    /**
     * Project name to filter batches by
     */
    project?: string;
    /**
     * Status to filter batches by (`staging` or `in_progress` or `completed`)
     */
    status?: string;
    /**
     * The minimum value of `created_at` for batches to be returned
     */
    startTime?: string;
    /**
     * The maximum value of `created_at` for batches to be returned
     */
    endTime?: string;
    /**
     * The minimum value of 'completed_at' for batches to be returned
     */
    completedAfter?: string;
    /**
     * The maximum value of 'completed_at' for batches to be returned
     */
    completedBefore?: string;
    /**
     * The minimum value of 'last_audited_at' for batches to be returned
     */
    auditedAfter?: string;
    /**
     * The maximum value of 'last_audited_at' for batches to be returned
     */
    auditedBefore?: string;
    /**
     * Number between 1&ndash;100, number of results per page (default 100)
     */
    limit?: number;
    /**
     * Number of results to skip for showing following pages (default 0)
     */
    offset?: number;
}
