/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const Annotations: core.serialization.ObjectSchema<serializers.Annotations.Raw, ScaleApi.Annotations> =
    core.serialization.object({
        objectsToAnnotate: core.serialization.property(
            "objects_to_annotate",
            core.serialization.list(core.serialization.string()).optional()
        ),
    });

export declare namespace Annotations {
    interface Raw {
        objects_to_annotate?: string[] | null;
    }
}
