/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const TaskGeometries: core.serialization.ObjectSchema<serializers.TaskGeometries.Raw, ScaleApi.TaskGeometries> =
    core.serialization.object({
        box: core.serialization.lazyObject(async () => (await import("../../..")).Annotations).optional(),
    });

export declare namespace TaskGeometries {
    interface Raw {
        box?: serializers.Annotations.Raw | null;
    }
}
