/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const TaskParams: core.serialization.ObjectSchema<serializers.TaskParams.Raw, ScaleApi.TaskParams> =
    core.serialization.object({
        attachment: core.serialization.string().optional(),
        geometries: core.serialization.lazyObject(async () => (await import("../../..")).TaskGeometries).optional(),
    });

export declare namespace TaskParams {
    interface Raw {
        attachment?: string | null;
        geometries?: serializers.TaskGeometries.Raw | null;
    }
}
