/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.studio.batches.setPriorities.Response.Raw,
    ScaleApi.studio.Batch[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../../../..")).studio.Batch));

export declare namespace Response {
    type Raw = serializers.studio.Batch.Raw[];
}
