/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CancelTasksRequest {
    /**
     * If `true`, will clear a task's `unique_id`, thus allowing the same unique id to be used in future tasks.
     */
    clearUniqueId?: string;
}
