/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListTasksRequest {
    /**
     * The minimum value of `created_at` for tasks to be returned
     */
    startTime?: string;
    /**
     * The maximum value of `created_at` for tasks to be returned
     */
    endTime?: string;
    /**
     * The minimum value of `completed_at` for tasks to be returned
     */
    completedAfter?: string;
    /**
     * The maximum value of `completed_at` for tasks to be returned
     */
    completedBefore?: string;
    /**
     * The minimum value of `updated_at` for tasks to be returned
     */
    updatedAfter?: string;
    /**
     * The maximum value of `updated_at` for tasks to be returned
     */
    updatedBefore?: string;
    /**
     * The status of the task - can be: `completed`, `pending`, or `canceled`
     */
    status?: string;
    /**
     * The type of the task
     */
    type?: string;
    /**
     * The name of the project that the returned tasks must belong to
     */
    project?: string;
    /**
     * The name of the batch that the returned tasks must belong to
     */
    batch?: string;
    /**
     * A number between 1 and 100, the maximum number of results to display per page | optional, default 100
     */
    limit?: number;
    /**
     * Set to true if the returned Task Object should include presigned attachment urls.
     */
    includeAttachmentUrl?: boolean;
    /**
     * A token used to retrieve the next page of results if there are more.
     */
    nextToken?: string;
}
