/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../../../core";

export const SetBatchGroupRequest: core.serialization.Schema<
    serializers.studio.SetBatchGroupRequest.Raw,
    ScaleApi.studio.SetBatchGroupRequest
> = core.serialization.object({
    groups: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace SetBatchGroupRequest {
    interface Raw {
        groups?: string[] | null;
    }
}
