/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../../core";

export const SetBatchPrioritiesRequest: core.serialization.Schema<
    serializers.studio.SetBatchPrioritiesRequest.Raw,
    Scale.studio.SetBatchPrioritiesRequest
> = core.serialization.object({
    groups: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../../../../..")).studio.BatchName))
        .optional(),
});

export declare namespace SetBatchPrioritiesRequest {
    interface Raw {
        groups?: serializers.studio.BatchName.Raw[] | null;
    }
}
