/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListProjectsRequest {
    /**
     * List information for only archived or only unarchived projects. If omitted, information for all projects will be listed.
     */
    archived?: boolean;
}
