/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const Batch: core.serialization.ObjectSchema<serializers.studio.Batch.Raw, ScaleApi.studio.Batch> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        name: core.serialization.string().optional(),
        projectId: core.serialization.string().optional(),
        projectName: core.serialization.string().optional(),
        batchType: core.serialization.string().optional(),
        studioPriority: core.serialization.number().optional(),
        total: core.serialization.number().optional(),
        completed: core.serialization.number().optional(),
        groups: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace Batch {
    interface Raw {
        id?: string | null;
        name?: string | null;
        projectId?: string | null;
        projectName?: string | null;
        batchType?: string | null;
        studioPriority?: number | null;
        total?: number | null;
        completed?: number | null;
        groups?: string[] | null;
    }
}
