/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const BatchName: core.serialization.ObjectSchema<serializers.studio.BatchName.Raw, ScaleApi.studio.BatchName> =
    core.serialization.object({
        name: core.serialization.string(),
    });

export declare namespace BatchName {
    interface Raw {
        name: string;
    }
}
