/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Client as AssignmentsClient } from "../resources/assignments/client/Client";
import { Client as BatchesClient } from "../resources/batches/client/Client";
import { Client as ProjectGroupsClient } from "../resources/projectGroups/client/Client";

export declare namespace Client {
    interface Options {
        environment?: environments.ScaleEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class Client {
    constructor(private readonly options: Client.Options) {}

    #assignments: AssignmentsClient | undefined;

    public get assignments(): AssignmentsClient {
        return (this.#assignments ??= new AssignmentsClient(this.options));
    }

    #batches: BatchesClient | undefined;

    public get batches(): BatchesClient {
        return (this.#batches ??= new BatchesClient(this.options));
    }

    #projectGroups: ProjectGroupsClient | undefined;

    public get projectGroups(): ProjectGroupsClient {
        return (this.#projectGroups ??= new ProjectGroupsClient(this.options));
    }
}
