/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Assignments } from "../resources/assignments/client/Client";
import { Batches } from "../resources/batches/client/Client";
import { ProjectGroups } from "../resources/projectGroups/client/Client";

export declare namespace Studio {
    interface Options {
        environment?: environments.ScaleEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class Studio {
    constructor(private readonly options: Studio.Options) {}

    private _assignments: Assignments | undefined;

    public get assignments(): Assignments {
        return (this._assignments ??= new Assignments(this.options));
    }

    private _batches: Batches | undefined;

    public get batches(): Batches {
        return (this._batches ??= new Batches(this.options));
    }

    private _projectGroups: ProjectGroups | undefined;

    public get projectGroups(): ProjectGroups {
        return (this._projectGroups ??= new ProjectGroups(this.options));
    }
}
