/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const Response: core.serialization.Schema<
    serializers.studio.assignments.list.Response.Raw,
    Record<string, Scale.studio.Assignment | undefined>
> = core.serialization.record(
    core.serialization.string(),
    core.serialization.lazy(async () => (await import("../../../../..")).studio.Assignment).optional()
);

export declare namespace Response {
    type Raw = Record<string, serializers.studio.Assignment.Raw | null | undefined>;
}
