/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const ProjectPramHistory: core.serialization.ObjectSchema<
    serializers.ProjectPramHistory.Raw,
    ScaleApi.ProjectPramHistory
> = core.serialization.object({
    instruction: core.serialization.string().optional(),
    version: core.serialization.number().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
});

export declare namespace ProjectPramHistory {
    interface Raw {
        instruction?: string | null;
        version?: number | null;
        created_at?: string | null;
    }
}
