/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ScaleApi } from "@fern-api/scale";

export interface ListTasksResponse {
    docs?: ScaleApi.Task[];
    total?: number;
    limit?: number;
    hasMore?: boolean;
    nextToken?: string;
}
