/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

export interface TaskParams {
    attachment?: string;
    geometries?: Scale.TaskGeometries;
}
