/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

export interface Task {
    taskId?: string;
    createdAt?: string;
    callbackUrl?: string;
    type?: string;
    status?: string;
    instruction?: string;
    params?: Scale.TaskParams;
    /** A set of key/value pairs that you can attach to a task object. It can be useful for storing additional information about the task in a structured format. Max 10KB. */
    metadata?: Record<string, unknown>;
}
