/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TaskType =
    | "annotation"
    | "categorization"
    | "comparison"
    | "cuboidannotation"
    | "datacollection"
    | "documentmodel"
    | "documenttranscription"
    | "imageannotation"
    | "laneannotation"
    | "lidarannotation"
    | "lidarlinking"
    | "lidarsegmentation"
    | "lidartopdown"
    | "lineannotation"
    | "namedentityrecognition"
    | "pointannotation"
    | "polygonannotation"
    | "segmentannotation"
    | "transcription"
    | "textcollection"
    | "videoannotation"
    | "videoboxannotation"
    | "videoplaybackannotation"
    | "videocuboidannotation";

export const TaskType = {
    Annotation: "annotation",
    Categorization: "categorization",
    Comparison: "comparison",
    CuboidAnnotation: "cuboidannotation",
    DataCollection: "datacollection",
    DocumentModel: "documentmodel",
    DocumentTranscription: "documenttranscription",
    ImageAnnotation: "imageannotation",
    LaneAnnotation: "laneannotation",
    LidarAnnotation: "lidarannotation",
    LidarLinking: "lidarlinking",
    LidarSegmentation: "lidarsegmentation",
    LidarTopdown: "lidartopdown",
    LineAnnotation: "lineannotation",
    NamedEntityRecognition: "namedentityrecognition",
    PointAnnotation: "pointannotation",
    PolygonAnnotation: "polygonannotation",
    SegmentAnnotation: "segmentannotation",
    Transcription: "transcription",
    TextCollection: "textcollection",
    VideoAnnotation: "videoannotation",
    VideoBoxAnnotation: "videoboxannotation",
    VideoPlaybackAnnotation: "videoplaybackannotation",
    VideoCuboidAnnotation: "videocuboidannotation",
} as const;
