/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../../core";

export const UpdateProjectGroupRequest: core.serialization.Schema<
    serializers.studio.UpdateProjectGroupRequest.Raw,
    Scale.studio.UpdateProjectGroupRequest
> = core.serialization.object({
    addEmails: core.serialization.property(
        "add_emails",
        core.serialization.list(core.serialization.string()).optional()
    ),
    removeEmails: core.serialization.property(
        "remove_emails",
        core.serialization.list(core.serialization.string()).optional()
    ),
});

export declare namespace UpdateProjectGroupRequest {
    interface Raw {
        add_emails?: string[] | null;
        remove_emails?: string[] | null;
    }
}
