/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const ProjectGroup: core.serialization.ObjectSchema<
    serializers.studio.ProjectGroup.Raw,
    ScaleApi.studio.ProjectGroup
> = core.serialization.object({
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    numWorkers: core.serialization.number().optional(),
    isSingleton: core.serialization.boolean().optional(),
    workers: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../../../..")).studio.Workers))
        .optional(),
});

export declare namespace ProjectGroup {
    interface Raw {
        id?: string | null;
        name?: string | null;
        numWorkers?: number | null;
        isSingleton?: boolean | null;
        workers?: serializers.studio.Workers.Raw[] | null;
    }
}
