/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../../core";

export const Workers: core.serialization.ObjectSchema<serializers.studio.Workers.Raw, Scale.studio.Workers> =
    core.serialization.object({
        id: core.serialization.string(),
        email: core.serialization.string(),
    });

export declare namespace Workers {
    interface Raw {
        id: string;
        email: string;
    }
}
