/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

export interface SetBatchPrioritiesRequest {
    groups?: Scale.studio.BatchName[];
}
