/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const Teammate: core.serialization.ObjectSchema<serializers.Teammate.Raw, ScaleApi.Teammate> =
    core.serialization.object({
        email: core.serialization.string(),
        role: core.serialization.string(),
        company: core.serialization.string().optional(),
        firstName: core.serialization.string().optional(),
        lastName: core.serialization.string().optional(),
        isStudioLabeler: core.serialization.boolean().optional(),
        expiry: core.serialization.string().optional(),
    });

export declare namespace Teammate {
    interface Raw {
        email: string;
        role: string;
        company?: string | null;
        firstName?: string | null;
        lastName?: string | null;
        isStudioLabeler?: boolean | null;
        expiry?: string | null;
    }
}
