/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CameraIntrinsics {
    fx?: number;
    fy?: number;
    cx?: number;
    cy?: number;
    skew?: number;
    scalefactor?: number;
}
