/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ScaleApi } from "@fern-api/scale";

export interface Cuboid {
    objectsToAnnotate?: unknown[];
    minHeight?: number;
    minWidth?: number;
    cameraIntrinsics?: ScaleApi.CameraIntrinsics;
    cameraRotationQuaternion?: ScaleApi.CameraRotationQuaternion;
    cameraHeight?: number;
}
