/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

/**
 * An object mapping `box`, `polygon`, `line`, `point`, `cuboid`, or `ellipse` to Geometry objects
 */
export interface Geometries {
    box?: Scale.Box;
    polygon?: Scale.Polygon;
    line?: Scale.Line;
    point?: Scale.Point;
    cuboid?: Scale.Cuboid;
    ellipse?: Scale.Ellipse;
}
