/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { ScaleApi } from "@fern-api/scale";

/**
 * An object mapping `box`, `polygon`, `line`, `point`, `cuboid`, or `ellipse` to Geometry objects
 */
export interface Geometries {
    box?: ScaleApi.Box;
    polygon?: ScaleApi.Polygon;
    line?: ScaleApi.Line;
    point?: ScaleApi.Point;
    cuboid?: ScaleApi.Cuboid;
    ellipse?: ScaleApi.Ellipse;
}
