/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Links {
    /** Whether or not the link is directional */
    isBidirectional?: boolean;
    /** a list of labels of the geometries that the link can be linked from */
    fromAllowedLabels?: unknown[];
    /** a list of labels of the geometries that the link can be linked to */
    toAllowedLabels?: unknown[];
}
