/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../core";

export const AnnotationAttribute: core.serialization.ObjectSchema<
    serializers.AnnotationAttribute.Raw,
    Scale.AnnotationAttribute
> = core.serialization.object({
    type: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    choices: core.serialization.string().optional(),
});

export declare namespace AnnotationAttribute {
    interface Raw {
        type?: string | null;
        description?: string | null;
        choices?: string | null;
    }
}
