/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const Box: core.serialization.ObjectSchema<serializers.Box.Raw, ScaleApi.Box> = core.serialization.object({
    objectsToAnnotate: core.serialization.property(
        "objects_to_annotate",
        core.serialization.list(core.serialization.unknown()).optional()
    ),
    minHeight: core.serialization.property("min_height", core.serialization.number().optional()),
    minWidth: core.serialization.property("min_width", core.serialization.number().optional()),
});

export declare namespace Box {
    interface Raw {
        objects_to_annotate?: unknown[] | null;
        min_height?: number | null;
        min_width?: number | null;
    }
}
