/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const CameraRotationQuaternion: core.serialization.ObjectSchema<
    serializers.CameraRotationQuaternion.Raw,
    ScaleApi.CameraRotationQuaternion
> = core.serialization.object({
    w: core.serialization.number().optional(),
    x: core.serialization.number().optional(),
    y: core.serialization.number().optional(),
    z: core.serialization.number().optional(),
});

export declare namespace CameraRotationQuaternion {
    interface Raw {
        w?: number | null;
        x?: number | null;
        y?: number | null;
        z?: number | null;
    }
}
