/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../core";

export const Ellipse: core.serialization.ObjectSchema<serializers.Ellipse.Raw, Scale.Ellipse> =
    core.serialization.object({
        objectsToAnnotate: core.serialization.property(
            "objects_to_annotate",
            core.serialization.list(core.serialization.unknown()).optional()
        ),
        vertices: core.serialization.list(core.serialization.unknown()).optional(),
    });

export declare namespace Ellipse {
    interface Raw {
        objects_to_annotate?: unknown[] | null;
        vertices?: unknown[] | null;
    }
}
