/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const Links: core.serialization.ObjectSchema<serializers.Links.Raw, ScaleApi.Links> = core.serialization.object({
    isBidirectional: core.serialization.property("is_bidirectional", core.serialization.boolean().optional()),
    fromAllowedLabels: core.serialization.property(
        "from_allowed_labels",
        core.serialization.list(core.serialization.unknown()).optional()
    ),
    toAllowedLabels: core.serialization.property(
        "to_allowed_labels",
        core.serialization.list(core.serialization.unknown()).optional()
    ),
});

export declare namespace Links {
    interface Raw {
        is_bidirectional?: boolean | null;
        from_allowed_labels?: unknown[] | null;
        to_allowed_labels?: unknown[] | null;
    }
}
