/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../core";

export const ObjectsToAnnotate: core.serialization.ObjectSchema<
    serializers.ObjectsToAnnotate.Raw,
    ScaleApi.ObjectsToAnnotate
> = core.serialization.object({
    objectsToAnnotate: core.serialization.property(
        "objects_to_annotate",
        core.serialization.list(core.serialization.unknown()).optional()
    ),
});

export declare namespace ObjectsToAnnotate {
    interface Raw {
        objects_to_annotate?: unknown[] | null;
    }
}
