/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../core";

export const VideoPlaybackAnnotationResponse: core.serialization.ObjectSchema<
    serializers.VideoPlaybackAnnotationResponse.Raw,
    Scale.VideoPlaybackAnnotationResponse
> = core.serialization.object({
    taskId: core.serialization.property("task_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    type: core.serialization.string().optional(),
    status: core.serialization.string().optional(),
    instruction: core.serialization.string().optional(),
    isTest: core.serialization.property("is_test", core.serialization.boolean().optional()),
    urgency: core.serialization.string().optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    project: core.serialization.string().optional(),
    callbackUrl: core.serialization.property("callback_url", core.serialization.string().optional()),
    updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
    workStarted: core.serialization.property("work_started", core.serialization.boolean().optional()),
    params: core.serialization.lazyObject(async () => (await import("../../..")).VideoPlaybackParams).optional(),
});

export declare namespace VideoPlaybackAnnotationResponse {
    interface Raw {
        task_id?: string | null;
        created_at?: string | null;
        type?: string | null;
        status?: string | null;
        instruction?: string | null;
        is_test?: boolean | null;
        urgency?: string | null;
        metadata?: Record<string, unknown> | null;
        project?: string | null;
        callback_url?: string | null;
        updated_at?: string | null;
        work_started?: boolean | null;
        params?: serializers.VideoPlaybackParams.Raw | null;
    }
}
