/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Scale } from "@fern-api/scale";

export interface ProjectGroup {
    /** Project group id */
    id?: string;
    /** Name of project group */
    name?: string;
    /** Number of workers in project group */
    numWorkers?: number;
    /** Is this project group for 1 teammate? */
    isSingleton?: boolean;
    workers?: Scale.studio.Workers[];
}
