/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AssignTeammate {
    /** Array of emails of teammates. */
    emails: string[];
    /** Array of projects to assign. */
    projects: string[];
}
