/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Batches } from "./api/resources/batches/client/Client";
import { Projects } from "./api/resources/projects/client/Client";
import { Studio } from "./api/resources/studio/client/Client";
import { Tasks } from "./api/resources/tasks/client/Client";
import { Teammates } from "./api/resources/teammates/client/Client";
import { Video } from "./api/resources/video/client/Client";

export declare namespace ScaleClient {
    interface Options {
        environment?: environments.ScaleEnvironment | string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}

export class ScaleClient {
    constructor(private readonly options: ScaleClient.Options) {}

    private _batches: Batches | undefined;

    public get batches(): Batches {
        return (this._batches ??= new Batches(this.options));
    }

    private _projects: Projects | undefined;

    public get projects(): Projects {
        return (this._projects ??= new Projects(this.options));
    }

    private _studio: Studio | undefined;

    public get studio(): Studio {
        return (this._studio ??= new Studio(this.options));
    }

    private _tasks: Tasks | undefined;

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this.options));
    }

    private _teammates: Teammates | undefined;

    public get teammates(): Teammates {
        return (this._teammates ??= new Teammates(this.options));
    }

    private _video: Video | undefined;

    public get video(): Video {
        return (this._video ??= new Video(this.options));
    }
}
