/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as BatchesClient } from "./api/resources/batches/client/Client";
import { Client as ProjectsClient } from "./api/resources/projects/client/Client";
import { Client as StudioClient } from "./api/resources/studio/client/Client";
import { Client as TasksClient } from "./api/resources/tasks/client/Client";
import { Client as TeammatesClient } from "./api/resources/teammates/client/Client";
import { Client as VideoClient } from "./api/resources/video/client/Client";

export declare namespace ScaleApiClient {
    interface Options {
        environment?: environments.ScaleApiEnvironment | string;
        token?: core.Supplier<core.BearerToken>;
    }
}

export class ScaleApiClient {
    constructor(private readonly options: ScaleApiClient.Options) {}

    #batches: BatchesClient | undefined;

    public get batches(): BatchesClient {
        return (this.#batches ??= new BatchesClient(this.options));
    }

    #projects: ProjectsClient | undefined;

    public get projects(): ProjectsClient {
        return (this.#projects ??= new ProjectsClient(this.options));
    }

    #studio: StudioClient | undefined;

    public get studio(): StudioClient {
        return (this.#studio ??= new StudioClient(this.options));
    }

    #tasks: TasksClient | undefined;

    public get tasks(): TasksClient {
        return (this.#tasks ??= new TasksClient(this.options));
    }

    #teammates: TeammatesClient | undefined;

    public get teammates(): TeammatesClient {
        return (this.#teammates ??= new TeammatesClient(this.options));
    }

    #video: VideoClient | undefined;

    public get video(): VideoClient {
        return (this.#video ??= new VideoClient(this.options));
    }
}
