/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ScaleApiEnvironment = {
    Production: "https://api.scale.com/v1/",
} as const;

export type ScaleApiEnvironment = typeof ScaleApiEnvironment.Production;
