/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ScaleEnvironment = {
    Production: "https://api.scale.com/v1/",
} as const;

export type ScaleEnvironment = typeof ScaleEnvironment.Production;
