/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<serializers.projects.list.Response.Raw, Scale.Project[]> =
    core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Project));

export declare namespace Response {
    type Raw = serializers.Project.Raw[];
}
