/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Batch {
    /** Batch id */
    id?: string;
    /** Batch name */
    name?: string;
    /** Project id */
    projectId?: string;
    /** Project name */
    projectName?: string;
    /** Batch type, can be `Production` or `Calibration` */
    batchType?: string;
    /** Priority of batch */
    studioPriority?: number;
    /** Total tasks in batch */
    total?: number;
    /** Completed tasks in batch */
    completed?: number;
    /** List of project groups in batch */
    groups?: string[];
}
