/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../core";

export const CreateProjectRequest: core.serialization.Schema<
    serializers.CreateProjectRequest.Raw,
    ScaleApi.CreateProjectRequest
> = core.serialization.object({
    type: core.serialization.lazy(async () => (await import("../../../..")).TaskType),
    name: core.serialization.string(),
    rapid: core.serialization.boolean().optional(),
    params: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace CreateProjectRequest {
    interface Raw {
        type: serializers.TaskType.Raw;
        name: string;
        rapid?: boolean | null;
        params?: Record<string, unknown> | null;
    }
}
