/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { ScaleApi } from "@fern-api/scale";
import * as core from "../../../../../core";

export const SetOntologyRequest: core.serialization.Schema<
    serializers.SetOntologyRequest.Raw,
    ScaleApi.SetOntologyRequest
> = core.serialization.object({
    ontology: core.serialization.list(core.serialization.unknown()),
    name: core.serialization.string().optional(),
});

export declare namespace SetOntologyRequest {
    interface Raw {
        ontology: unknown[];
        name?: string | null;
    }
}
