/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { Scale } from "@fern-api/scale";
import * as core from "../../../../../core";

export const UpdateProjectParametersRequest: core.serialization.Schema<
    serializers.UpdateProjectParametersRequest.Raw,
    Scale.UpdateProjectParametersRequest
> = core.serialization.object({
    patch: core.serialization.boolean().optional(),
    instruction: core.serialization.string().optional(),
});

export declare namespace UpdateProjectParametersRequest {
    interface Raw {
        patch?: boolean | null;
        instruction?: string | null;
    }
}
